# Generated by Django 2.1.1 on 2018-09-27 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField()),
                ('credit_score', models.IntegerField()),
                ('credit_rating', models.CharField(max_length=5)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_credit_reports',
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField()),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit_reports', models.ManyToManyField(related_name='financial_reports', to='credit_report.CreditReport')),
            ],
            options={
                'db_table': 'app_financial_reports',
            },
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=9, max_digits=99)),
                ('financials_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financials', to='credit_report.FinancialReport')),
            ],
            options={
                'db_table': 'app_financials',
            },
        ),
        migrations.CreateModel(
            name='RiskDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=9, max_digits=99)),
                ('financial_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_drivers', to='credit_report.FinancialReport')),
            ],
            options={
                'db_table': 'app_risk_drivers',
            },
        ),
    ]
