# Generated by Django 2.1.2 on 2018-10-25 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_report', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField(db_index=True)),
                ('probability_of_default', models.DecimalField(decimal_places=2, max_digits=9)),
                ('credit_rating', models.CharField(max_length=5)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('financial_reports', models.ManyToManyField(related_name='credit_reports', to='financial_report.FinancialReport')),
                ('news', models.ManyToManyField(related_name='credit_reports', to='news.News')),
            ],
            options={
                'db_table': 'app_credit_reports',
            },
        ),
    ]
