# Generated by Django 2.1.2 on 2018-10-25 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField(db_index=True)),
                ('title', models.TextField(db_index=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('snippet', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'app_news',
            },
        ),
    ]
