# Generated by Django 2.2 on 2019-04-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRatingModel',
            fields=[
                ('order', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default=None, editable=False, max_length=5)),
            ],
            options={
                'db_table': 'app_credit_ratings',
            },
        ),
    ]
