# Generated by Django 2.2 on 2019-06-10 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True, editable=False)),
                ('probability_of_default', models.DecimalField(decimal_places=2, editable=False, max_digits=9)),
                ('risk_rating', models.CharField(editable=False, max_length=5)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'app_risk_reports',
                'ordering': ['-date_time'],
            },
        ),
    ]
