# Generated by Django 2.1.2 on 2018-10-05 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('industry', models.TextField(db_index=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'app_companies',
            },
        ),
    ]
