# Generated by Django 2.1.2 on 2018-10-29 04:22

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, default=None, unique=True)),
                ('industry', models.TextField(db_index=True, default=None)),
                ('description', models.TextField(default=None)),
                ('exchange', models.TextField(db_index=True, default=None)),
                ('country', django_countries.fields.CountryField(db_index=True, default=None, max_length=2)),
            ],
            options={
                'db_table': 'app_companies',
            },
        ),
    ]
