# Generated by Django 2.1.1 on 2018-09-27 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('industry', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'app_companies',
            },
        ),
    ]
