# Generated by Django 2.2 on 2019-06-10 05:41

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, default=None, editable=False, unique=True)),
                ('industry', models.TextField(db_index=True, default=None, editable=False)),
                ('description', models.TextField(default=None, editable=False)),
                ('exchange', models.TextField(db_index=True, default=None, editable=False)),
                ('country', django_countries.fields.CountryField(db_index=True, default=None, editable=False, max_length=2)),
            ],
            options={
                'db_table': 'app_companies',
            },
        ),
    ]
